services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  serverless-redis-http:
    ports:
      - "8079:80"
    image: hiett/serverless-redis-http:latest
    environment:
      SRH_MODE: env
      SRH_TOKEN: uFPXfm1s5Iz5kvxSZp6vDWZybms5uR1F0EJMFF2yGw
      SRH_CONNECTION_STRING: "redis://redis:6379"
      SRH_MAX_CONNECTIONS: 100
  
  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
